import { Product } from '../types/product';

export const MOCK_PRODUCTS: Product[] = [
  // RAMPS
  {
    id: 'r1',
    name: 'Warped Woods Ramp',
    category: 'Ramps',
    price: 45.0,
    rating: 4.8,
    description: 'Precision-engineered wooden ramp with a smooth finish for perfect dice rolls.',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Material', value: 'Walnut Wood' },
      { label: 'Angle', value: '35 Degrees' },
      { label: 'Weight', value: '450g' },
    ],
    tags: ['Wood', 'Premium', 'Handmade'],
  },
  {
    id: 'r2',
    name: 'Neon Acrylic Slider',
    category: 'Ramps',
    price: 35.0,
    rating: 4.5,
    description: 'High-visibility neon green acrylic ramp, perfect for low-light gaming sessions.',
    imageUrl: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Material', value: 'Acrylic' },
      { label: 'Color', value: 'Neon Green' },
      { label: 'Portability', value: 'Collapsible' },
    ],
    tags: ['Acrylic', 'Neon', 'Modern'],
  },
  // DECKS
  {
    id: 'd1',
    name: 'Vault Commander Box',
    category: 'Decks',
    price: 60.0,
    rating: 4.9,
    description: 'Ultra-durable deck box designed to hold 100+ double-sleeved cards securely.',
    imageUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Capacity', value: '100+ Sleeved Cards' },
      { label: 'Material', value: 'Synthetic Leather' },
      { label: 'Closure', value: 'Magnetic' },
    ],
    tags: ['Standard', 'Double-Sleeved', 'Premium'],
  },
  {
    id: 'd2',
    name: 'Modular Deck Organizer',
    category: 'Decks',
    price: 25.0,
    rating: 4.2,
    description: 'Interlocking deck organizers for multi-deck players and board game storage.',
    imageUrl: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Capacity', value: '60 Cards per unit' },
      { label: 'Material', value: 'PLA (3D Printed)' },
      { label: 'Feature', value: 'Stackable' },
    ],
    tags: ['Modular', '3D Printed', 'Lightweight'],
  },
  // DICE TOWERS
  {
    id: 'dt1',
    name: 'The Citadel Tower',
    category: 'Dice Tower',
    price: 85.0,
    rating: 5.0,
    description: 'An epic, architectural masterpiece designed to look like a fantasy fortress.',
    imageUrl: 'https://images.unsplash.com/photo-1589127077399-d2975fe94b1e?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Height', value: '25cm' },
      { label: 'Material', value: 'Resin' },
      { label: 'Base', value: 'Felt-lined Tray' },
    ],
    tags: ['Featured', 'Epic', 'Fantasy'],
  },
  {
    id: 'dt2',
    name: 'Steampunk Gearbox',
    category: 'Dice Tower',
    price: 55.0,
    rating: 4.7,
    description: 'Mechanical-themed dice tower with moving gears (visual only) and sound-dampening interior.',
    imageUrl: 'https://images.unsplash.com/photo-1544329010-3d9f4d7dd665?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Style', value: 'Steampunk' },
      { label: 'Material', value: 'Plywood' },
      { label: 'Assembly', value: 'Pre-assembled' },
    ],
    tags: ['Modular', 'Mechanical', 'Wood'],
  },
  // ACESSÓRIOS
  {
    id: 'a1',
    name: 'Midnight Life Counter',
    category: 'Acessórios',
    price: 15.0,
    rating: 4.6,
    description: 'Sleek, dual-dial life counter with neon accents for competitive play.',
    imageUrl: 'https://images.unsplash.com/photo-1553481187-be93c21490a9?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Range', value: '0-99' },
      { label: 'Material', value: 'Metal' },
      { label: 'Size', value: 'Pocket' },
    ],
    tags: ['Para RPG', 'Counters'],
  },
  {
    id: 'a2',
    name: 'Obsidian Dice Set',
    category: 'Acessórios',
    price: 40.0,
    rating: 4.8,
    description: 'Hand-carved volcanic glass dice set with sharp edges and gold numbering.',
    imageUrl: 'https://images.unsplash.com/photo-1519326844852-704caea5679e?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Set', value: '7-piece RPG' },
      { label: 'Material', value: 'Obsidian' },
      { label: 'Inlay', value: 'Gold Foil' },
    ],
    tags: ['Custom Dice', 'Para RPG'],
  },
  // XADREZ
  {
    id: 'x1',
    name: 'Grandmaster Walnut Set',
    category: 'Xadrez',
    price: 250.0,
    rating: 5.0,
    description: 'Professional-grade chess set featuring a solid walnut board and weighted boxwood pieces.',
    imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Board Size', value: '50x50cm' },
      { label: 'Material', value: 'Walnut & Maple' },
      { label: 'Weighting', value: 'Triple-weighted' },
    ],
    tags: ['Complete Sets', 'Premium'],
  },
  {
    id: 'x2',
    name: 'Carbon Fiber Travel Board',
    category: 'Xadrez',
    price: 120.0,
    rating: 4.4,
    description: 'Modern, lightweight carbon fiber board with magnetic pieces for chess on the go.',
    imageUrl: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&q=80&w=800',
    specs: [
      { label: 'Material', value: 'Carbon Fiber' },
      { label: 'Type', value: 'Magnetic' },
      { label: 'Weight', value: '1.2kg' },
    ],
    tags: ['Boards Only', 'Modern'],
  },
];
